services:
  postgres-auth:
    container_name: postgres-auth
    image: postgres:18-alpine
    ports:
      - 5433:5432
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER_AUTH}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER_AUTH}",
          "-d",
          "${POSTGRES_DB_AUTH}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-wallet:
    container_name: postgres-wallet
    image: postgres:18-alpine
    ports:
      - 5434:5432
    volumes:
      - pgdata-wallet:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER_WALLET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_WALLET}
      POSTGRES_DB: ${POSTGRES_DB_WALLET}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER_WALLET}",
          "-d",
          "${POSTGRES_DB_WALLE}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

volumes:
  pgdata-auth:
  pgdata-wallet:
  rabbitmq_data:
