services:
  postgres-wallet:
    container_name: postgres-wallet
    image: postgres:16-alpine
    ports:
      - 5435:5432
    volumes:
      - pgdata-wallet:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER_WALLET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_WALLET}
      POSTGRES_DB: ${POSTGRES_DB_WALLET}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER_WALLET}",
          "-d",
          "${POSTGRES_DB_WALLET}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-net

volumes:
  pgdata-wallet:

networks:
  dev-net:
    driver: bridge
