services:
  auth-service:
    container_name: auth-service
    image: node:20-alpine
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    env_file: .env
    depends_on:
      postgres-auth:
        condition: service_healthy
      redis-auth:
        condition: service_healthy

  redis-auth:
    container_name: redis-auth
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASSWORD_AUTH}",
      ]
    volumes:
      - redis-data-auth:/data
    env_file: .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping", "-a", "${REDIS_PASSWORD_AUTH}"]
      interval: 5s
      timeout: 2s
      retries: 5

  redis-test-auth:
    container_name: redis-test-auth
    image: redis:7-alpine
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes"]

  postgres-auth:
    container_name: postgres-auth
    image: postgres:16-alpine
    ports:
      - 5433:5432
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER_AUTH}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER_AUTH}",
          "-d",
          "${POSTGRES_DB_AUTH}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-auth-test:
    container_name: postgres-auth-test
    image: postgres:16-alpine
    ports:
      - 5434:5432
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER_AUTH_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH_TEST}
      POSTGRES_DB: ${POSTGRES_DB_AUTH_TEST}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER_AUTH_TEST}",
          "-d",
          "${POSTGRES_DB_AUTH_TEST}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-wallet:
    container_name: postgres-wallet
    image: postgres:16-alpine
    ports:
      - 5435:5432
    volumes:
      - pgdata-wallet:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER_WALLET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_WALLET}
      POSTGRES_DB: ${POSTGRES_DB_WALLET}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER_WALLET}",
          "-d",
          "${POSTGRES_DB_WALLET}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

volumes:
  pgdata-auth:
  redis-data-auth:
  pgdata-wallet:
  rabbitmq-data:
