services:
  auth-service-test:
    container_name: auth-service-test
    image: node:20-alpine
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.test
    ports:
      - 3000:3000
    depends_on:
      postgres-auth-test:
        condition: service_healthy
      redis-auth-test:
        condition: service_healthy

  redis-auth-test:
    container_name: redis-auth-test
    image: redis:7-alpine
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres-auth-test:
    container_name: postgres-auth-test
    image: postgres:16-alpine
    ports:
      - 5434:5432
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER_AUTH_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH_TEST}
      POSTGRES_DB: ${POSTGRES_DB_AUTH_TEST}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER_AUTH_TEST}",
          "-d",
          "${POSTGRES_DB_AUTH_TEST}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
