name: Auth Service CI

on:
  pull_request:
    branches:
      - main
    paths:
      - services/auth-service/**
  push:
    branches:
      - main
    paths:
      - services/auth-service/**

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./services/auth-service
        run: yarn install

      - name: Run lint
        working-directory: ./services/auth-service
        run: yarn lint

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./services/auth-service
        run: yarn install

      - name: Run unit tests
        working-directory: ./services/auth-service
        run: yarn test

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    env:
      DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER_AUTH }}:${{ secrets.POSTGRES_PASSWORD_AUTH }}@localhost:5432/${{ secrets.POSTGRES_DB_AUTH }}?schema=public
      JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
      JWT_ACCESS_TOKEN_TIME: ${{ secrets.JWT_ACCESS_TOKEN_TIME }}
      JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
      JWT_REFRESH_TOKEN_TIME: ${{ secrets.JWT_REFRESH_TOKEN_TIME }}
      REDIS_USE_TLS_AUTH: ${{ secrets.REDIS_USE_TLS_AUTH }}
      REDIS_URL_AUTH: ${{ secrets.REDIS_URL_AUTH }}

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER_AUTH }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_AUTH }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB_AUTH }}
        options: >-
          --health-cmd="pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"

      redis:
        image: redis:7
        options: >-
          --save "" --appendonly no --health-cmd="redis-cli ping"

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./services/auth-service
        run: yarn install

      - name: Prepare test database
        working-directory: ./services/auth-service
        run: yarn db:test

      - name: Run E2E tests
        working-directory: ./services/auth-service
        run: yarn test:e2e

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: e2e-tests

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./services/auth-service
        run: yarn install

      - name: Generate Prisma Client
        working-directory: ./services/auth-service
        run: npx prisma generate

      - name: Build project
        working-directory: ./services/auth-service
        run: yarn build

  docker:
    name: Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build & Push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest ./services/auth-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
