name: Auth Service CI

on:
  pull_request:
    branches:
      - main
    paths:
      - services/auth-service/**
  push:
    branches:
      - main
    paths:
      - services/auth-service/**

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./services/auth-service
        run: yarn install

      - name: Run lint
        working-directory: ./services/auth-service
        run: yarn lint

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./services/auth-service
        run: yarn install

      - name: Run unit tests
        working-directory: ./services/auth-service
        run: yarn test

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    env:
      NODE_ENV: test
      POSTGRES_USER: ${{ secrets.POSTGRES_USER_AUTH_TEST }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_AUTH_TEST }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB_AUTH_TEST }}
      DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER_AUTH_TEST }}:${{ secrets.POSTGRES_PASSWORD_AUTH_TEST }}@localhost:5432/${{ secrets.POSTGRES_DB_AUTH_TEST }}
      JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
      JWT_ACCESS_TOKEN_TIME: ${{ secrets.JWT_ACCESS_TOKEN_TIME }}
      JWT_REFRESH_TOKEN_TIME: ${{ secrets.JWT_REFRESH_TOKEN_TIME }}
      REDIS_HOST_AUTH_TEST: ${{ secrets.REDIS_HOST_AUTH_TEST }}
      REDIS_PORT_AUTH_TEST: ${{ secrets.REDIS_PORT_AUTH_TEST }}
      REDIS_PASSWORD_AUTH_TEST: ${{ secrets.REDIS_PASSWORD_AUTH_TEST }}

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd="pg_isready -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }}"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

      redis:
        image: redis:7

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./services/auth-service
        run: yarn install

      - name: Prepare test database
        working-directory: ./services/auth-service
        run: yarn db:test

      - name: Run E2E tests
        working-directory: ./services/auth-service
        run: yarn test:e2e

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: e2e-tests

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./services/auth-service
        run: yarn install

      - name: Generate Prisma Client
        working-directory: ./services/auth-service
        run: npx prisma generate

      - name: Build project
        working-directory: ./services/auth-service
        run: yarn build

  docker:
    name: Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build & Push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest ./services/auth-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
