name: Auth Service CI

on:
  pull_request:
    branches:
      - main
    paths:
      - services/auth-service/**
  push:
    branches:
      - main
    paths:
      - services/auth-service/**

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install packages
        working-directory: ./services/auth-service
        run: yarn install

      - name: Run lint
        working-directory: ./services/auth-service
        run: yarn lint

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./services/auth-service
        run: yarn install

      - name: Build project
        working-directory: ./services/auth-service
        run: yarn build

  docker:
    name: Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build & Push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest ./services/auth-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
